### ISSUE TITLE
Eclipse: HTTP Proxy Authentication Required

### ISSUE THREAD

**Issue by boson666** [spring-projects/eclipse-integration-tcserver#12]
Hi,
I would like to install Pivotal tc server runtime on my Eclipse. I'm spending all my energy, always with the same proxy error. I read a lot of things on the Internet, but now I have to admit that I'm tired. Why is it still so complicated in the Open world? If it continues I will definitely abandoned the server tc. Could you explain to me please? My Eclipse is in version 4.11.

HTTP Proxy Authentication Required: https://dist.springsource.com/release/TOOLS/eclipse-integration-tcserver/content.xml
Proxy Authentication Required

 Thank you in advance.

**Comment by martinlippert** [comment]
I am not sure what exactly you are trying to accomplish here. If you want to install the Eclipse Integration for Pivotal tc Server, you can either go via the Eclipse Marketplace and install it from there or use the update site directly:

https://dist.springsource.com/release/TOOLS/eclipse-integration-tcserver/

This URL is not meant to be used via a browser, but to be used in the "Install New Software" dialog inside of Eclipse (just in case, some people often get confused about that piece).

If you are hitting a proxy authentication issue while doing that, you might be connected to the network via a proxy server (on your side somewhere) that requires authentication. In that case, you would need to configure your network settings in Eclipse accordingly. Since that is a network connection setting on your side, there is nothing we can do about it to make it easier - to be honest.

In addition to that, please be reminded that installing the tc Server integration plugin into Eclipse doesn't come with an actual "Pivotal tc Server" itself, which you could get here: https://network.pivotal.io/products/pivotal-tcserver.

Hope this helps!

**Comment by boson666** [comment]
Hello, thank you for your message. I know everything you explain to me, but when you read all the problems people have to install your pluggins directly or not in Eclipse, you can imagine that you could let your packages download directly and then install them locally. Why block the url? I may not be the smartest, but I'm tired of not being able to directly download your packages directly and being confronted with proxy issues that will have no solution at all. Too bad, it was an opportunity for me to integrate Pivotal tc server to the Société Générale, Boursorama, Crédit du Nord, La Banque Postale, and Crédit Agricole.

Best regards.

Christophe DUVAL
06 19 77 11 73

**Comment by martinlippert** [comment]
@boson666 First of all, we do not control the overall mechanism to install plugins into an existing Eclipse installation and we DO NOT block anything. We offer a well-defined p2 repository that people can use to install Spring Tools components into an existing Eclipse installation - as this is done for Eclipse itself, too. If our users are running into problems installing the tools into an existing Eclipse installation, we are happy to help.

You are referring to "but when you read all the problems people have to install your plugins directly or not in Eclipse". We would be happy to talk to them and help - as we always do. So if you are aware of users who are running into problems, please do not hesitate to contact us and I am sure we will find a solution for those issues.

In addition to that, we do indeed offer ready-to-use Eclipse distributions that you can just download and use, including the Spring Tools pre-installed. Therefore I don't know what you mean by "but I'm tired of not being able to directly download your packages directly". Go to https://spring.io/tools and download the Spring Tools 4 for Eclipse distribution packages, they have the Spring Tools pre-installed.

If you are specifically interested in tc Server, it comes bundled with the old Spring Tool Suite 3 distribution, again ready-to-use. You can download those packages from https://spring.io/tools3/sts/all. Having that said, those packages are being EOL by mid of next year.

Let me know if you need anything else here. I think there are a bunch of options available (as described) and we are happy to help with further issues. Let us know the details and we are happy to help. And if you want us to help with the companies that you mentioned, please do also not hesitate to contact us directly.

**Comment by boson666** [comment]
Thank you for your new message. What I would like is a zip file of your https://dist.springsource.com/release/TOOLS/eclipse-integration-tcserver/ <https://dist.springsource.com/release/TOOLS/eclipse-integration-tcserver/> to then make a local installation under Eclipse.

Best regards.

Christophe DUVAL
06 19 77 11 73

**Comment by martinlippert** [comment]
Sure, no problem, here you go (latest release):
https://dist.springsource.com/release/TOOLS/eclipse-integration-tcserver/3.9.10.RELEASE/eclipse-integration-tcserver-3.9.10.201909171224-RELEASE-updatesite.zip

Please keep in mind that this requires components in your Eclipse installation that are typically part of the Eclipse JEE package. So in case you don't have that as a base install, installing the tc Server integration will probably try to grab additional components from the main Eclipse repo - just as a heads-up.

**Comment by boson666** [comment]
Hello,

thank you very much. I got the repo, and I have a problem with a json component for the workspace.

Cannot complete the install because one or more required items could not be found.
  Software being installed: Spring Tool Suite Common UI Components 3.9.10.201909170647-RELEASE (org.springsource.ide.eclipse.commons.ui 3.9.10.201909170647-RELEASE)
  Missing requirement: Spring Tool Suite Common UI Components 3.9.10.201909170647-RELEASE (org.springsource.ide.eclipse.commons.ui 3.9.10.201909170647-RELEASE) requires 'osgi.bundle; org.json 1.0.0' but it could not be found



Best regards.

Christophe DUVAL
06 19 77 11 73

**Comment by martinlippert** [comment]
Yes, that looks like once of those components that are part of the Eclipse release train and coming from their update repository. Do you have access to that? Or would you need to have an offline version of that, too?

I could include that dependency in our p2 repo quickly for your convenience. In that case, you would need to download a CI build of our tc Server Integration p2 repo. What do you think?

**Comment by boson666** [comment]
Thank you for your message. Indeed, if you can provide me with a complete p2, it can simplify my life.

Best regards

Christophe DUVAL
06 19 77 11 73

**Comment by martinlippert** [comment]
Here you are, I added the necessary bundles to the p2 repo. This allows the tc-server integration to be installed into an Eclipse JEE package (I tested this with Eclipse JEE 2019-09) without contacting other updates sites during the install.

This is not released yet, but you can use the CI p2 repo here:
https://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly

Or download the ZIP of the repo here:
https://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly/eclipse-integration-tcserver-3.9.11.201911211006-CI-B130-updatesite.zip

Please note that this is a URL to the CI build, which gets invalid as soon as the next CI build kicks in and deletes the previous one. I don't expect very frequent CI builds of the tc-server integration, but just in case someone comes back to this at a later time - this URL is a temporary one.

Hope this helps!

**Comment by boson666** [comment]
Hello,

Thank you very much for the bundle I installed successfully on Eclipse. I had tears in my eyes, it was so beautiful, a pure moment of happiness, an immense joy, a rebirth, the desire to go further, to climb the mountains and touch the sky, …

I am not familiar with the Pivotal TC Server, I discovered the server to help a team that migrates their application from Websphere ZOS on redhat. By declaring a Pivotal TC Server runtime on my Eclipse, I discovered the notion of template. I want to be able to develop a classic http / https WEB application on a tomcat 8.5 base with version 3.2.11 of Pivtoal TC Server. I do not know what the APR is. I will read everything I find on the net. Maybe you can tell me how to add templates in Eclipse. Thanks again.





Best regards,

Life is too short to remove USB safely. 

Christophe DUVAL
06 19 77 11 73

**Comment by kdvolder** [comment]
@boson666 This is somewhat unrelated to your questions about TcServer.... but have you (or the team you are helping) considered switching to using spring-boot jar packaging? With this more modern approach to packaging your applications you do not need to worry at all about installing / managing servers like tomcat, TcServer or whatever to deploy your 'war' apps into. Instead the app is completely self-contained and comes with an embedded server instance (which by default is tomcat, but can be switched easily to something else).

Not sure how practical this approach would be for you. But if you haven't thought about it before it may be something worth looking into.

All our tooling is really moving in the direction of supporting modern jar-packaged boot apps, and the TcServer tooling is in 'low maintenance' mode already and is not very well supported. 

> Maybe you can tell me how to add templates in Eclipse.

Unfortunately, I'm not familiar with defining new templates. So I can't help you with that unfortunately.

**Comment by martinlippert** [comment]
@boson666 In case you would like to learn more about tc Server, here is the link to the docs: https://tcserver.docs.pivotal.io/4x/docs-tcserver/topics/about-tc-server.html

**Comment by boson666** [comment]
Hi, thanks for the information..

Christophe DUVAL
06 19 77 11 73

**Comment by boson666** [comment]
hi, thanks for your message. In the end, I will migrate to a tomcat and then I will see to use pivotal.

Christophe DUVAL
06 19 77 11 73
