### ISSUE TITLE
During the creation of a server instance, a connection is made to repo.pivotal.io where local proxy settings are ignored.

### ISSUE THREAD

**Issue by patbaumgartner** [spring-projects/eclipse-integration-tcserver#13]
Setting up a new tc-server-developer instance with the VMware TC Server Integration for Eclipse and a "Server Template for 4.1.3" standard and developer fails with the following stack trace on windows. 

Important to mention we are in an enterprise environment where we are behind a proxy. Plugin installation via Marketplace works!

Error creating server instance with command:
 "C:\tc-server-developer\pivotal-tc-server-standard-4.1.3.RELEASE\pivotal-tc-server\standard-4.1.3.RELEASE\tcserver.bat create z202-base-instance -v 9.0.36.B.RELEASE -t nio -t base --property base.runtime.user=null --java-home C:\java\java-14-openjdk-14.0.1.7-1.windows.redhat.x86_64". Check access permission for the directory C:/tc-server-developer/pivotal-tc-server-standard-4.1.3.RELEASE/pivotal-tc-server/standard-4.1.3.RELEASE and its files and subdirectories.
  The instance creation command failed and returned code 1
  Output of the instance creation command:
'create' command failed. An unexpected error occurred while attempting to validate tc Runtime Version 9.0.36.B.RELEASE: Connect to repo.pivotal.io:443 [repo.pivotal.io/54.164.122.42, repo.pivotal.io/34.232.37.107] failed: Connect timed out

I made sure that read-only is not set and all user have full control.

Any idea how to fix it?

**Comment by BoykoAlex** [comment]
Not sure... I grabbed tc server 4.1.3 (with Tomcat 9.0.36 runtime)... it created instance with **base** and **nio** templates fine. Tried the same with open JDK 14.0.1 - also worked.
Did you create Runtime Environment using the VMware category rather than Pivotal?
Maybe try creating tc server instance using just the CLI executing the command you have in the description above... wonder if it has to do anything with the IDE...

**Comment by patbaumgartner** [comment]
Wow, thanks for the fast feedback. 

Yes used VMware category, used Java 14 with base and nio templates too. But did not manage it to create a Server via CLI on Windows because it said that the printed IP is not a command.

Will try with a fresh STS installation now again and provide feedback.

**Comment by patbaumgartner** [comment]
It's definitely a CLI/tc-server script issue and not related to this plugin. Will close the ticket and find a way to provide the proxies to the script. Thank you @BoykoAlex for your support!
