### ISSUE TITLE
pivotal-tc-server-developer-4.0.9.RELEASE and higher: The Tomcat installation directory is not valid. It is missing expected file or folder lib.

### ISSUE THREAD

**Issue by patbaumgartner** [spring-projects/eclipse-integration-tcserver#14]
**Summary:**
Downloading the pivotal-tc-server-developer version greater than 4.0.9 and loading it to STS leads to this error message.
![image](https://user-images.githubusercontent.com/406780/90398461-c05a8f80-e099-11ea-8439-6d8b23bee8f4.png)

**Expected:**
Using pivotal-tc-server-developer-4.0.8.RELEASE and pivotal-tc-server-developer-4.0.9.RELEASE and loading it in STS with the tc-server plugin works fine. Important to mention that I created things from scratch. No other releases in the pivotal-tc-server directory.

**Issue:**
With a version from 4.0.10 and higher (current 4.0.15), the validation fails as seen in the image. Checking the content of the zip files looks like nothing is missing and only version numbers of the dependencies are different. 

**Workaround:**
Downloading pivotal-tc-server-developer-4.0.9.RELEASE and pivotal-tc-server-developer-4.0.15.RELEASE and extracting them to the same folder allows me to choose the current tomcat release 9.0.36.B.RELEASE. The creation of the instance works!

Unfortunately, I could not find the error message in this code, and also not in the pivotal-tc-server scripts. 

Best,
Patrick

**Comment by BoykoAlex** [comment]
Thanks veru much for the bug report. Fixed with 0bd5c7718b7c6327ad791524f1fd6d1666a992de.

The fix should be available in the nightly update site: https://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly in a few hours from now

**Comment by martinlippert** [comment]
New release 4.1.1, which contains the fix, available from:

https://download.springsource.com/release/TOOLS/eclipse-integration-tcserver

**Comment by patbaumgartner** [comment]
Thank you @BoykoAlex and @martinlippert very much. I tested it and it works now for two-digit version numbers :))
