### ISSUE TITLE
[tc server 4.x] Existing server instances combo is always empty

### ISSUE THREAD

**Issue by lak-proddev** [spring-projects/eclipse-integration-tcserver#6]
tc server 4.0 server wizard  is not showing any existing instances.It showing empty list.

![tc_empty_list](https://user-images.githubusercontent.com/39690425/41757890-94697520-7602-11e8-8406-2c0fce614fde.png)

I think, new directory structure  for tc server 4.x is causing the issue.

TcServer21WizardFragment.java at lines 295-306 
// add all directories that have a server configuration
File file = path.toFile();
if (file.exists()) {
 File[] serverDirectories = file.listFiles();
 if (serverDirectories != null) {
  **for (File directory : serverDirectories) {
   if (directory.isDirectory() && new File(directory, ".tc-runtime-instance").exists()) {
    serverNameCombo.add(directory.getName());
   }
  }**
 }
}

**Comment by BoykoAlex** [comment]
Should be fixed now. Please try http://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly
