### ISSUE TITLE
[tc server 4.x] Unable to start tc server 4.0.1

### ISSUE THREAD

**Issue by lak-proddev** [spring-projects/eclipse-integration-tcserver#7]
Unable to start the  tc server 4.0.1 developer edition. Which has **_"ajp"_** server instance. Even  for other templates also.

**_Wed Jun 20 13:42:07 IST 2018 ran with arguments: create test_instance -v 9.0.7.B.RELEASE -t ajp --java-home C:\Program Files\Java\jdk1.8.0_144_** 

Server start is failing  with timeout exception.  I think, as per the log the actual server is starting. But, server status is not being updated on view. 

See attached exception **(Not related)**
[tc_server_Start_exception.txt](https://github.com/spring-projects/eclipse-integration-tcserver/files/2126752/tc_server_Start_exception.txt)

See attached  SS

![tc_server_fail1](https://user-images.githubusercontent.com/39690425/41760412-f01f46e8-7610-11e8-9858-3ce97cc40511.png)

![tc_server_fail2](https://user-images.githubusercontent.com/39690425/41760411-efcd69ea-7610-11e8-9e51-9fcf05b7e035.png)

**Comment by BoykoAlex** [comment]
Should be fixed now. Try nightly build: http://dist.springsource.com/snapshot/TOOLS/eclipse-integration-tcserver/nightly

**Comment by lak-proddev** [comment]
Thank you very much for quick response. :)

**Comment by lak-proddev** [comment]
Still, I can  starting issue  on **_ajp_** instance.

Pivotal tc Server Integration for Eclipse	3.9.5.201806221714-CI-B95

**Comment by BoykoAlex** [comment]
If you can install it from the nightly tc Server integration site and it works then it hasn't made into the STS distro build probably... Try a fresher 3.9.5 STS build perhaps.
