### ISSUE TITLE
[tc server] selecting  "serve modules without publishing"  option is  failing with exception.

### ISSUE THREAD

**Issue by lak-proddev** [spring-projects/eclipse-integration-tcserver#8]
selecting  **_serve modules without publishing_**  option is  failing with exception.
See below SS

_Loader jar not found for server ID: org.eclipse.jst.server.tomcat.runtime.90._

![image](https://user-images.githubusercontent.com/39690425/41888362-bacd7db0-7922-11e8-9c3a-46154cff1dfb.png)

**Comment by BoykoAlex** [comment]
should be fixed now

**Comment by lak-proddev** [comment]
Thanks for the fix. But, the commit only fixes the exception. Actual  option doesn't work properly.

I think, this issue will be fixed by overriding  this method  in tc server code.`org.eclipse.jst.server.tomcat.core.internal.TomcatServerBehaviour.publishFinish(IProgressMonitor)` 

We need to map tc server id to tomcat runtime Id.

See this line

TomcatServerBehaviour.java line 352 
String tomcatVersion = TomcatVersionHelper.getCatalinaVersion(getServer().getRuntime().getLocation(), serverTypeID);

com.vmware.vfabric.ide.eclipse.tcserver.internal.core.TcServerVersionHandler.mapToTomcatRuntimeId(IPath, String)

**Comment by BoykoAlex** [comment]
Hopefully fixed now. Since you're diving into the source code feel free to create PRS for stuff you find not working. We'll gladly merge them :-)

FYI: I see that deploying to tc server 3.x with tomcat 7.0.x isn't working but everything else seems to be in order. Looking into it now.

**Comment by BoykoAlex** [comment]
NVM, it deploys fine, just need to create proper boot app

**Comment by lak-proddev** [comment]
Still, I couldn't deploy application. I think, this would be the fix.

[Issue-8tc-server-selecting-serve-modules-without-pub.txt](https://github.com/spring-projects/eclipse-integration-tcserver/files/2140010/Issue-8tc-server-selecting-serve-modules-without-pub.txt)

**Comment by martinlippert** [comment]
Would you be interested in submitting this as a pull request? In case so, please make sure to read the guidelines for contributing code and sign the contributors license agreement: https://github.com/spring-projects/eclipse-integration-tcserver/blob/master/CONTRIBUTING.adoc

That would be fantastic!!!
